"use client"

import * as React from "react"

export type Locale = "en" | "pt-BR"

/** Map app locale to BCP 47 locale string used by Intl date/time APIs */
const DATE_LOCALE_MAP: Record<Locale, string> = {
  en: "en-US",
  "pt-BR": "pt-BR",
}

const translations = {
  en: {
    // Home page
    "home.subtitle":
      "View your exported WhatsApp conversations — entirely in your browser.",
    "home.private": "100% Private",
    "home.privateDesc": "Nothing leaves your device",
    "home.instant": "Instant",
    "home.instantDesc": "Parsed entirely in your browser",
    "home.fullMedia": "Full Media",
    "home.fullMediaDesc": "Images, video, audio & docs",

    // Upload zone
    "upload.extracting": "Extracting ZIP...",
    "upload.parsing": "Parsing messages...",
    "upload.largeChat": "This may take a moment for large chats",
    "upload.dropHere": "Drop your file here",
    "upload.dropExport": "Drop your WhatsApp export here",
    "upload.browseHint": "or click to browse. Accepts .zip files only",
    "upload.invalidFile": "Please upload a .zip file exported from WhatsApp.",
    "upload.noMessages": "No messages found in the chat file.",
    "upload.failedProcess": "Failed to process file.",

    // Viewer page
    "viewer.loading": "Loading...",

    // Chat view
    "chat.messages": "messages",
    "chat.media": "media",
    "chat.searchPlaceholder": "Search messages...",
    "chat.results": "results",

    // Message bubble
    "message.deleted": "This message was deleted",
    "message.edited": "edited",

    // Media gallery
    "mediaGallery.title": "Shared Media",
    "mediaGallery.images": "Images",
    "mediaGallery.videos": "Videos",
    "mediaGallery.audio": "Audio",
    "mediaGallery.docs": "Docs",
    "mediaGallery.noImages": "No images shared in this chat",
    "mediaGallery.noVideos": "No videos shared in this chat",
    "mediaGallery.noAudio": "No audio shared in this chat",
    "mediaGallery.noDocuments": "No documents shared in this chat",
    "mediaGallery.audioMessage": "Audio message",
    "mediaGallery.document": "Document",
    "mediaGallery.fullSizePreview": "Full size preview",

    // Media preview
    "mediaPreview.unavailable": "Media unavailable",
    "mediaPreview.audioProgress": "Audio progress",

    // Theme
    "theme.toggle": "Toggle theme",

    // Participant avatar
    "participant.removePhoto": "Remove photo",

    // Edit mode toolbar
    "editMode.editMode": "Edit Mode",
    "editMode.selected": "selected",
    "editMode.deselectAll": "Deselect all",
    "editMode.selectAll": "Select all",
    "editMode.exportPdf": "Export PDF",
    "editMode.exitEditMode": "Exit edit mode",

    // Message selector
    "messageSelector.messages": "Messages",

    // Timeline preview
    "timeline.title": "Timeline",
    "timeline.emptyState":
      "Select messages from the left panel to build your timeline",
    "timeline.message": "message",
    "timeline.messages": "messages",
    "timeline.of": "of",
    "timeline.note": "Note",
    "timeline.editNote": "Edit note",
    "timeline.addNote": "Add note",

    // Comment editor
    "commentEditor.notes": "Notes",
    "commentEditor.emptyState":
      'Click "Add note" on a day block to write comments',
    "commentEditor.closeEditor": "Close editor",
    "commentEditor.bold": "Bold",
    "commentEditor.italic": "Italic",
    "commentEditor.underline": "Underline",
    "commentEditor.bulletList": "Bullet list",
    "commentEditor.orderedList": "Ordered list",
    "commentEditor.link": "Link",
    "commentEditor.urlPrompt": "URL:",

    // PDF export
    "pdf.title": "Chat Timeline",
    "pdf.note": "NOTE",
    "pdf.footer": "Generated by Zaping on",
    "pdf.message": "message",
    "pdf.messages": "messages",
    "pdf.of": "of",
    "pdf.filename": "chat-timeline.pdf",
    "pdf.appendix": "Full Conversation Log",
    "pdf.appendixDesc":
      "Complete messages for all days included in the timeline",

    // Extract zip
    "extract.noChatFile":
      "No chat text file found in the ZIP. Expected a file like _chat.txt or WhatsApp Chat with *.txt",

    // Language selector
    "lang.english": "English",
    "lang.portuguese": "Portuguese",
  },
  "pt-BR": {
    // Home page
    "home.subtitle":
      "Visualize suas conversas exportadas do WhatsApp — totalmente no seu navegador.",
    "home.private": "100% Privado",
    "home.privateDesc": "Nada sai do seu dispositivo",
    "home.instant": "Instantaneo",
    "home.instantDesc": "Processado inteiramente no seu navegador",
    "home.fullMedia": "Midia Completa",
    "home.fullMediaDesc": "Imagens, video, audio e documentos",

    // Upload zone
    "upload.extracting": "Extraindo ZIP...",
    "upload.parsing": "Processando mensagens...",
    "upload.largeChat": "Isso pode levar um momento para conversas grandes",
    "upload.dropHere": "Solte seu arquivo aqui",
    "upload.dropExport": "Solte sua exportacao do WhatsApp aqui",
    "upload.browseHint": "ou clique para buscar. Aceita apenas arquivos .zip",
    "upload.invalidFile":
      "Por favor, envie um arquivo .zip exportado do WhatsApp.",
    "upload.noMessages": "Nenhuma mensagem encontrada no arquivo de conversa.",
    "upload.failedProcess": "Falha ao processar arquivo.",

    // Viewer page
    "viewer.loading": "Carregando...",

    // Chat view
    "chat.messages": "mensagens",
    "chat.media": "midia",
    "chat.searchPlaceholder": "Buscar mensagens...",
    "chat.results": "resultados",

    // Message bubble
    "message.deleted": "Esta mensagem foi apagada",
    "message.edited": "editada",

    // Media gallery
    "mediaGallery.title": "Midia Compartilhada",
    "mediaGallery.images": "Imagens",
    "mediaGallery.videos": "Videos",
    "mediaGallery.audio": "Audio",
    "mediaGallery.docs": "Docs",
    "mediaGallery.noImages": "Nenhuma imagem compartilhada nesta conversa",
    "mediaGallery.noVideos": "Nenhum video compartilhado nesta conversa",
    "mediaGallery.noAudio": "Nenhum audio compartilhado nesta conversa",
    "mediaGallery.noDocuments": "Nenhum documento compartilhado nesta conversa",
    "mediaGallery.audioMessage": "Mensagem de audio",
    "mediaGallery.document": "Documento",
    "mediaGallery.fullSizePreview": "Visualizacao em tamanho real",

    // Media preview
    "mediaPreview.unavailable": "Midia indisponivel",
    "mediaPreview.audioProgress": "Progresso do audio",

    // Theme
    "theme.toggle": "Alternar tema",

    // Participant avatar
    "participant.removePhoto": "Remover foto",

    // Edit mode toolbar
    "editMode.editMode": "Modo Edicao",
    "editMode.selected": "selecionadas",
    "editMode.deselectAll": "Desmarcar todas",
    "editMode.selectAll": "Selecionar todas",
    "editMode.exportPdf": "Exportar PDF",
    "editMode.exitEditMode": "Sair do modo edicao",

    // Message selector
    "messageSelector.messages": "Mensagens",

    // Timeline preview
    "timeline.title": "Linha do Tempo",
    "timeline.emptyState":
      "Selecione mensagens no painel esquerdo para construir sua linha do tempo",
    "timeline.message": "mensagem",
    "timeline.messages": "mensagens",
    "timeline.of": "de",
    "timeline.note": "Nota",
    "timeline.editNote": "Editar nota",
    "timeline.addNote": "Adicionar nota",

    // Comment editor
    "commentEditor.notes": "Notas",
    "commentEditor.emptyState":
      'Clique em "Adicionar nota" em um bloco de dia para escrever comentarios',
    "commentEditor.closeEditor": "Fechar editor",
    "commentEditor.bold": "Negrito",
    "commentEditor.italic": "Italico",
    "commentEditor.underline": "Sublinhado",
    "commentEditor.bulletList": "Lista com marcadores",
    "commentEditor.orderedList": "Lista numerada",
    "commentEditor.link": "Link",
    "commentEditor.urlPrompt": "URL:",

    // PDF export
    "pdf.title": "Linha do Tempo da Conversa",
    "pdf.note": "NOTA",
    "pdf.footer": "Gerado pelo Zaping em",
    "pdf.message": "mensagem",
    "pdf.messages": "mensagens",
    "pdf.of": "de",
    "pdf.filename": "linha-do-tempo-conversa.pdf",
    "pdf.appendix": "Registro Completo da Conversa",
    "pdf.appendixDesc":
      "Todas as mensagens dos dias incluidos na linha do tempo",

    // Extract zip
    "extract.noChatFile":
      "Nenhum arquivo de texto de conversa encontrado no ZIP. Esperado um arquivo como _chat.txt ou WhatsApp Chat com *.txt",

    // Language selector
    "lang.english": "Ingles",
    "lang.portuguese": "Portugues",
  },
} as const

export type TranslationKey = keyof (typeof translations)["en"]

type I18nContextValue = {
  locale: Locale
  dateLocale: string
  setLocale: (locale: Locale) => void
  t: (key: TranslationKey) => string
}

const I18nContext = React.createContext<I18nContextValue | null>(null)

const STORAGE_KEY = "zaping-locale"

function I18nProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = React.useState<Locale>("en")

  // Load saved locale on mount
  React.useEffect(() => {
    const saved = localStorage.getItem(STORAGE_KEY)
    if (saved === "en" || saved === "pt-BR") {
      setLocaleState(saved)
    }
  }, [])

  const setLocale = React.useCallback((newLocale: Locale) => {
    setLocaleState(newLocale)
    localStorage.setItem(STORAGE_KEY, newLocale)
    document.documentElement.lang = newLocale === "pt-BR" ? "pt-BR" : "en"
  }, [])

  const t = React.useCallback(
    (key: TranslationKey): string => {
      return translations[locale][key] ?? translations.en[key] ?? key
    },
    [locale]
  )

  const dateLocale = DATE_LOCALE_MAP[locale]

  const value = React.useMemo(
    () => ({ locale, dateLocale, setLocale, t }),
    [locale, dateLocale, setLocale, t]
  )

  return <I18nContext value={value}>{children}</I18nContext>
}

function useI18n(): I18nContextValue {
  const context = React.useContext(I18nContext)
  if (!context) {
    throw new Error("useI18n must be used within an I18nProvider")
  }
  return context
}

/**
 * Get a translation function for non-component code (e.g. lib utilities).
 * Falls back to reading from localStorage directly.
 */
function getTranslation(key: TranslationKey): string {
  let locale: Locale = "en"
  if (typeof window !== "undefined") {
    const saved = localStorage.getItem(STORAGE_KEY)
    if (saved === "en" || saved === "pt-BR") {
      locale = saved
    }
  }
  return translations[locale][key] ?? translations.en[key] ?? key
}

/**
 * Get the BCP 47 date locale string for non-component code.
 * Falls back to reading from localStorage directly.
 */
function getDateLocale(): string {
  let locale: Locale = "en"
  if (typeof window !== "undefined") {
    const saved = localStorage.getItem(STORAGE_KEY)
    if (saved === "en" || saved === "pt-BR") {
      locale = saved
    }
  }
  return DATE_LOCALE_MAP[locale]
}

export { I18nProvider, useI18n, getTranslation, getDateLocale }
